POST  http://localhost:3003/api/users
content-type: application/json

#     {
#     "blogs": [],
#     "username": "AshaaM",
#     "name": "Asaha",
#     "password": "passAshaa"
# }

{
    "blogs": [],
    "username": "Ashaa",
     "name": "Ashaa",
    "password": "passAshaa"
}

