PUT http://localhost:3003/api/blogs/61f7379ebf40302ea7ef16ce
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkRlbGwiLCJpZCI6IjYxZjczNzllYmY0MDMwMmVhN2VmMTZjZSIsImlhdCI6MTY0NDk3MjcxMSwiZXhwIjoxNjQ0OTg3MTExfQ.K7Ft-rFi-aiZibJP1tRLV_M5eYn-0m_TKg0Qp5RnENw

{
  "title": "Testing cypress",
       "author": "Ashaa Muhunthan",
          "url": "https://testing.com",
        "likes": 3
  }
